### ISSUE TITLE
Allow setting of the number of minimum replicas and extraManifests

### ISSUE THREAD

**Issue by wolviecb** [clemlesne/azure-pipelines-agent#103]
Hi,

Thanks for the great work setting this repo! :)

I've noticed that when setting the `ScaleJob` you hard coded the `minReplicaCount` number to `0`. While I understand the rationale of setting it to `0` I also wanted it to be possible to set it to an arbitrary value. 

I've also wanted to be able to not pass secrets as plain text on the chart, it would be helpful to be able to create the secret apart from the main helm chart (e. g.: using sealed secrets and passing on the encrypted manifest)

I've created [a PR](https://github.com/clemlesne/azure-pipelines-agent/pull/102) that adds these features :)

**Comment by clemlesne** [comment]
Version `6.2.0` deployed, that's for you! :)
