### ISSUE TITLE
Chart 5.0.0 - KubeVersion: >=1.19

### ISSUE THREAD

**Issue by hugobritobh** [clemlesne/azure-pipelines-agent#13]
Using version 5, in the linux environment I have problem. 

chart requires kubeVersion: >=1.19 which is incompatible with Kubernetes v1.26.2-eks

_Locally I made the correction by removing this requirement._

**Comment by clemlesne** [comment]
Hello, just pushed a fix on feat/fix-kubeversion-selector (f0a61f99b49a61e82b1f70a0863341811fa20b0b). Can you try to give me feedback?

**Comment by hugobritobh** [comment]
It worked 👍 

Thanks

**Comment by clemlesne** [comment]
Merged: 3b10e1d399b796b3c8889f2b6d4bfce29fe388d1
