### ISSUE TITLE
Version 5.2.1

### ISSUE THREAD

**Issue by hugobritobh** [clemlesne/azure-pipelines-agent#19]
EKS 1.26
Image: Jammy

I did a quick test and got the following error (folder ***) :

time="2023-05-11T12:27:57Z" level=warning msg="/proc/sys/ *** /max_ *** _namespaces needs to be set to non-zero."
error: failed to list workers: Unavailable: connection error: desc = "transport: error while dialing: dial unix /run/ *** /0/buildkit/buildkitd.sock: connect: no such file or directory"

**Comment by clemlesne** [comment]
The issue with this configuration seems to be known for AWS Linux image, Bottlerocket.

It seems required to change the configuration of the node by setting `user.max_user_namespaces` configuration to a large level.

Can you try to apply [this config](https://github.com/moby/buildkit/blob/v0.11.6/examples/kubernetes/sysctl-userns.privileged.yaml)?

**Comment by hugobritobh** [comment]
Of course, but I can answer you maybe tomorrow

**Comment by clemlesne** [comment]
I added details in the doc, see: 631f9380e2e41711c54e2bdaaa3005c72463d4da.
