### ISSUE TITLE
larger consumption of ephemeral-storage

### ISSUE THREAD

**Issue by hugobritobh** [clemlesne/azure-pipelines-agent#22]
I had a problem compiling a large image on linux (Image Jammy 5.2.1). 

I put the **cache** and **tmpdir** with **40G** and the following error occurs

**ephemeral-storage. Threshold quantity: ,available: Ki. Container azp-agent was using  ││ Ki, request is 0, has larger consumption of ephemeral-storage**

When I put ephemeral-storage in the Request, the PVC is in Peding status and the POD does not run...

resources:
  requests:
    cpu: 1000m
    memory: 2Gi
    ephemeral-storage: 20Gi
    
  I'm analyzing if there is any wrong configuration in the volumes

**Comment by clemlesne** [comment]
Ephemeral storage is usually limited to the amount of local disk on the node. Can you confirm that hypothesis?

Note: I'm strongly discouraging you using `emptyDir` as their performance is mediocre (at best) and can slow down the Kubernetes Node. But I understand that ephemeral private volumes are not available everywhere.

**Comment by hugobritobh** [comment]
Today I managed to test again and I got the following analysis:

Ta writing in the "overlay" in another volume ("root folder").

Responsible for this is the **buildkit** (snapshots folder)

root@azp-agent-linux-azure-pipelines-agent-ghk6t-slbrw:**/var/lib/buildkit/runc-native**# du -hs * | sort -h
4.6G    **snapshots**

the volumes are being created correctly:
![volumes](https://github.com/clemlesne/azure-pipelines-agent/assets/8490666/14f4ef11-22ee-4005-b6a4-21b8d5722064)

I will research if there is a possibility to record these **snapshots** in another folder

**Comment by hugobritobh** [comment]
In my scenario it is interesting to write in another volume. 

To change I put this command in the pipeline and it worked correctly:

_echo 'root = "/app-root/.local/tmp/buildkit"' > /etc/buildkit/buildkitd.toml
echo 'root = "/app-root/.local/tmp/buildkit"' > ~/.config/buildkit/buildkitd.toml_
