### ISSUE TITLE
Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement

### ISSUE THREAD

**Issue by archerixx** [clemlesne/azure-pipelines-agent#3]
Issue:
Building Azure Agent with helm on openshift (https://artifacthub.io/packages/helm/azure-pipelines-agent/azure-pipelines-agent) causes issue on pod. It requires licence to be approved upon configuration, which is not possible since pod is being unmanaged.

Adding following configuration into template should resolve this issue:
--unattended - agent setup will not prompt for information, and all settings must be provided on the command line

Thank you

**Comment by clemlesne** [comment]
Hello @archerixx,

The `--unattended` flag is already defined and the license automatically approved with `--acceptTeeEula` ([see sources](https://github.com/clemlesne/azure-pipelines-agent/blob/bf66ab3e7e4c628b4880300f947fd976a4210424/src/docker/start.sh#L46)). I'm unable to reproduce your issue.

Did you try one of [the pre-built images](https://github.com/clemlesne/azure-pipelines-agent#compatibility)?

**Comment by archerixx** [comment]
After restarting helm build, issue was gone. Thank you for your help.

**Comment by clemlesne** [comment]
May I ask why you are rebuilding locally the containers and Helm chart?
