### ISSUE TITLE
Needing more permissions at $HOME

### ISSUE THREAD

**Issue by defaultbr** [clemlesne/azure-pipelines-agent#35]
Hi @clemlesne , I've added kubectl cli using your image as base, so my dockerfile looks like this:

```
FROM ghcr.io/clemlesne/azure-pipelines-agent:jammy-main

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
```

the error thru the pipeline agent:

command: `kubectl config set-credentials "name" --token="token"`

```
error: mkdir /app-root/.kube: permission denied
error: mkdir /app-root/.kube: permission denied
error: mkdir /app-root/.kube: permission denied
```

If I build and do a normal `docker run -it image:1 bash` and try to configure the kubectl, It works as expected, but thru the vstsagent running no.

Off-topic: is it possible to add some kind of container runner (not only builder)? I've tried to install podman, docker, ctr (containerd), but I can't pass the error about the `is docker sock running?` or `running as pid 1, systemd not found` or `"/" is not a shared dir`

**Comment by defaultbr** [comment]
The solution for my case:

```
FROM ghcr.io/clemlesne/azure-pipelines-agent:jammy-main

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN mkdir -m 777 /agent-work <--------
ENV HOME=/agent-work  <-------
```

**Comment by clemlesne** [comment]
Branch [feat/rw-permissions-home](https://github.com/clemlesne/azure-pipelines-agent/tree/feat/rw-permissions-home) created. Can you validate the agent build against your pipeline?

**Comment by clemlesne** [comment]
Poke @defaultbr

**Comment by defaultbr** [comment]
Hi @clemlesne, we changed the rules about deployment inside my company, so we had to plan a new way using direct vms, sorry for the late answer. Thank you so much, probably in the future I will return to try this out.
