### ISSUE TITLE
Improvements to make job completion more flexible

### ISSUE THREAD

**Issue by paulocappelli-cit** [clemlesne/azure-pipelines-agent#63]
Hi!

There is the possibility to include customization for flags:

Keda (https://keda.sh/docs/2.10/concepts/scaling-jobs/#scaledjob-spec)
- successfulJobsHistoryLimit
- failedJobsHistoryLimit

Job (into ScaledJob) https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs
- ttlSecondsAfterFinished

The intention is to have greater flexibility on the completion of jobs/scaleJobs and greater control related to the volumes created in cloud.

Tks!

**Comment by clemlesne** [comment]
Thank you for your proposal 😄 Configuration options have been added (b4a86018440c43f312aa2249f3e867d61620ff1d).

**Is it what you thought about?**

Documentation extract:

| Parameter                        | Description                                                                                                                                                                                                                                                                                              | Default                                                                                                                                                         |
| -------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `pipelines.cleanup.ttl`          | Delay until Job history will be cleaned from Kubernetes API server ([see doc](https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs)). Only applied to autoscaled deployments (see `autoscaling.enabled`).                                                      | `3600` (1 hour)                                                                                                                                                 |
| `pipelines.cleanup.failed`       | Maximum of failed Jobs to keep from Kubernetes API server ([see doc](https://keda.sh/docs/2.11/concepts/scaling-jobs/#scaledjob-spec)). Only applied to autoscaled deployments (see `autoscaling.enabled`).                                                                                              | `100`                                                                                                                                                           |
| `pipelines.cleanup.successful`   | Maximum of successful Jobs to keep from Kubernetes API server ([see doc](https://keda.sh/docs/2.11/concepts/scaling-jobs/#scaledjob-spec)). Only applied to autoscaled deployments (see `autoscaling.enabled`).                                                                                          | `100`                                                                                                                                                           |

**Comment by paulocappelli-cit** [comment]
Yes!!

Tks @clemlesne
